<pre>
<img align="center" width="300" src="https://raw.githubusercontent.com/andrelmfsantos/ppga/master/logo%20uninove.png">
</pre>

<pre>
<img align="center" width="150" src="https://camo.githubusercontent.com/bdc6a3b8963aa99ff57dfd6e1e4b937bd2e752bcb1f1936f90368e5c3a38f670/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4c6963656e73652d434325323042592d2d5341253230342e302d6c69676874677265792e737667">
</pre>

<h1 style="text-align:center;">Estatística Bayesiana com Julia Language Programming</h1>

|                 |              |
|:----------------|:-------------|
|**Universidade:**| Nove de Julho|
|**Programa:**    | PPGI - Programa de Pós Graduação em Informática |
|**Disciplina:**  | Estatística Bayesiana com Julia|
|**Atividade:**   | Desenvolvimento de base de dados para atividade final da disciplina|
|**Professor:**   | José E. Storopoli|
|**Aluno:**       | André L.M.F.Santos|

In [1]:
# Importar pacotes necessários
import Pkg; Pkg.add("HTTP"); Pkg.add("DataFrames"); Pkg.add("CSV")

    Updating registry at `C:\Users\User\.julia\registries\General.toml`
   Resolving package versions...
  No Changes to `C:\Users\User\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\User\.julia\environments\v1.8\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\User\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\User\.julia\environments\v1.8\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\User\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\User\.julia\environments\v1.8\Manifest.toml`

In [2]:
# Carregar pacotes
using HTTP, DataFrames, Dates, CSV

In [3]:
# Ativo de interesse
acao = "GOLL4"

"GOLL4"

In [4]:
# Carregar dados
r = HTTP.get("https://query1.finance.yahoo.com/v7/finance/download/"*acao*".SA?period1=1640995200&period2=1662508800&interval=1d&events=history&includeAdjustedClose=true");
data = String(r.body);

In [5]:
# Dados
data

"Date,Open,High,Low,Close,Adj Close,Volume\n2022-01-03,17.209999,17.469999,16.580000,16.740000,16.740000,5537500\n2022-01-04,16.959999,16.990000,16.250000,16.340000,16.340000,3137800\n2022-01-05,16.110001,16.190001,15.230000,15.230000,15.230000,5173300\n2022-01-06,15.390000," ⋯ 11238 bytes ⋯ "022-09-01,10.050000,10.390000,9.680000,10.260000,10.260000,12132200\n2022-09-02,10.460000,10.500000,9.920000,9.990000,9.990000,11938000\n2022-09-05,10.090000,10.120000,9.880000,10.030000,10.030000,4671200\n2022-09-06,10.050000,10.140000,9.390000,9.520000,9.520000,10747700"

In [6]:
# Preparação da base
csv_data = replace(data,"Date,Open,High,Low,Close,Adj Close,Volume\n"=>"") # remove cabeçalho
csv_data = split(csv_data, "\n")                                           # separa strings por "\n"

172-element Vector{SubString{String}}:
 "2022-01-03,17.209999,17.469999,16.580000,16.740000,16.740000,5537500"
 "2022-01-04,16.959999,16.990000,16.250000,16.340000,16.340000,3137800"
 "2022-01-05,16.110001,16.190001,15.230000,15.230000,15.230000,5173300"
 "2022-01-06,15.390000,15.650000,14.860000,15.500000,15.500000,4699400"
 "2022-01-07,15.270000,15.990000,15.100000,15.770000,15.770000,3765500"
 "2022-01-10,15.750000,15.770000,15.340000,15.700000,15.700000,4616200"
 "2022-01-11,15.730000,16.290001,15.570000,16.170000,16.170000,3976800"
 "2022-01-12,16.170000,16.700001,16.020000,16.700001,16.700001,4457800"
 "2022-01-13,16.500000,17.129999,16.360001,16.750000,16.750000,4435500"
 "2022-01-14,16.660000,16.930000,16.430000,16.930000,16.930000,2748300"
 "2022-01-17,16.850000,17.049999,16.530001,16.770000,16.770000,1869000"
 "2022-01-18,16.620001,16.830000,16.280001,16.379999,16.379999,3633200"
 "2022-01-19,16.549999,17.340000,16.320000,16.450001,16.450001,5933500"
 ⋮
 "2022-08-22,10.270000,10.300000,9.940000,10.240000,10.240000,6309200"
 "2022-08-23,10.280000,10.940000,10.240000,10.940000,10.940000,6282300"
 "2022-08-24,10.940000,11.600000,10.850000,11.300000,11.300000,7512600"
 "2022-08-25,11.410000,12.150000,11.310000,11.920000,11.920000,10438200"
 "2022-08-26,12.010000,12.200000,11.350000,11.480000,11.480000,12200200"
 "2022-08-29,11.290000,11.600000,11.010000,11.090000,11.090000,10990700"
 "2022-08-30,11.440000,11.510000,10.240000,10.400000,10.400000,15188900"
 "2022-08-31,10.480000,10.680000,10.030000,10.100000,10.100000,12331300"
 "2022-09-01,10.050000,10.390000,9.680000,10.260000,10.260000,12132200"
 "2022-09-02,10.460000,10.500000,9.920000,9.990000,9.990000,11938000"
 "2022-09-05,10.090000,10.120000,9.880000,10.030000,10.030000,4671200"
 "2022-09-06,10.050000,10.140000,9.390000,9.520000,9.520000,10747700"

In [7]:
# Criar dataframe
df = DataFrame([csv_data],[:x1])
first(df, 5)

5×1 DataFrame
 Row │ x1
     │ SubStrin…
─────┼───────────────────────────────────
   1 │ 2022-01-03,17.209999,17.469999,1…
   2 │ 2022-01-04,16.959999,16.990000,1…
   3 │ 2022-01-05,16.110001,16.190001,1…
   4 │ 2022-01-06,15.390000,15.650000,1…
   5 │ 2022-01-07,15.270000,15.990000,1…

In [8]:
# Separar coluna em múltiplas colunas
transform!(df, :x1 => ByRow(x -> split(x, ",")) => [:Y1, :Y2, :Y3, :Y4, :Y5, :Y6, :Y7])
show(df, allcols=true)

172×8 DataFrame
 Row │ x1                                 Y1          Y2         Y3         Y4         Y5         Y6         Y7
     │ SubStrin…                          SubStrin…   SubStrin…  SubStrin…  SubStrin…  SubStrin…  SubStrin…  SubStrin…
─────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ 2022-01-03,17.209999,17.469999,1…  2022-01-03  17.209999  17.469999  16.580000  16.740000  16.740000  5537500
   2 │ 2022-01-04,16.959999,16.990000,1…  2022-01-04  16.959999  16.990000  16.250000  16.340000  16.340000  3137800
   3 │ 2022-01-05,16.110001,16.190001,1…  2022-01-05  16.110001  16.190001  15.230000  15.230000  15.230000  5173300
   4 │ 2022-01-06,15.390000,15.650000,1…  2022-01-06  15.390000  15.650000  14.860000  15.500000  15.500000  4699400
   5 │ 2022-01-07,15.270000,15.990000,1…  2022-01-07  15.270000  15.990000  15.100000  15.770000  15.770000  3765500
   6 │ 2022-01-10,15.750000,15.770000,1…  2022-01-10  15.750000  15.770000  15.340000  15.700000  15.700000  4616200
   7 │ 2022-01-11,15.730000,16.290001,1…  2022-01-11  15.730000  16.290001  15.570000  16.170000  16.170000  3976800
   8 │ 2022-01-12,16.170000,16.700001,1…  2022-01-12  16.170000  16.700001  16.020000  16.700001  16.700001  4457800
   9 │ 2022-01-13,16.500000,17.129999,1…  2022-01-13  16.500000  17.129999  16.360001  16.750000  16.750000  4435500
  10 │ 2022-01-14,16.660000,16.930000,1…  2022-01-14  16.660000  16.930000  16.430000  16.930000  16.930000  2748300
  11 │ 2022-01-17,16.850000,17.049999,1…  2022-01-17  16.850000  17.049999  16.530001  16.770000  16.770000  1869000
  ⋮  │                 ⋮                      ⋮           ⋮          ⋮          ⋮          ⋮          ⋮          ⋮
 163 │ 2022-08-24,10.940000,11.600000,1…  2022-08-24  10.940000  11.600000  10.850000  11.300000  11.300000  7512600
 164 │ 2022-08-25,11.410000,12.150000,1…  2022-08-25  11.410000  12.150000  11.310000  11.920000  11.920000  10438200
 165 │ 2022-08-26,12.010000,12.200000,1…  2022-08-26  12.010000  12.200000  11.350000  11.480000  11.480000  12200200
 166 │ 2022-08-29,11.290000,11.600000,1…  2022-08-29  11.290000  11.600000  11.010000  11.090000  11.090000  10990700
 167 │ 2022-08-30,11.440000,11.510000,1…  2022-08-30  11.440000  11.510000  10.240000  10.400000  10.400000  15188900
 168 │ 2022-08-31,10.480000,10.680000,1…  2022-08-31  10.480000  10.680000  10.030000  10.100000  10.100000  12331300
 169 │ 2022-09-01,10.050000,10.390000,9…  2022-09-01  10.050000  10.390000  9.680000   10.260000  10.260000  12132200
 170 │ 2022-09-02,10.460000,10.500000,9…  2022-09-02  10.460000  10.500000  9.920000   9.990000   9.990000   11938000
 171 │ 2022-09-05,10.090000,10.120000,9…  2022-09-05  10.090000  10.120000  9.880000   10.030000  10.030000  4671200
 172 │ 2022-09-06,10.050000,10.140000,9…  2022-09-06  10.050000  10.140000  9.390000   9.520000   9.520000   10747700
                                                                                                       151 rows omitted

In [9]:
# Renomear colunas
select!(df,
    "Y1" => "Date",
    "Y2" => "Open",
    "Y3" => "High",
    "Y4" => "Low",
    "Y5" => "Close",
    "Y6" => "Adj_Close",
    "Y7" => "Volume")

172×7 DataFrame
 Row │ Date        Open       High       Low        Close      Adj_Close  Volu ⋯
     │ SubStrin…   SubStrin…  SubStrin…  SubStrin…  SubStrin…  SubStrin…  SubS ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 2022-01-03  17.209999  17.469999  16.580000  16.740000  16.740000  5537 ⋯
   2 │ 2022-01-04  16.959999  16.990000  16.250000  16.340000  16.340000  3137
   3 │ 2022-01-05  16.110001  16.190001  15.230000  15.230000  15.230000  5173
   4 │ 2022-01-06  15.390000  15.650000  14.860000  15.500000  15.500000  4699
   5 │ 2022-01-07  15.270000  15.990000  15.100000  15.770000  15.770000  3765 ⋯
   6 │ 2022-01-10  15.750000  15.770000  15.340000  15.700000  15.700000  4616
   7 │ 2022-01-11  15.730000  16.290001  15.570000  16.170000  16.170000  3976
   8 │ 2022-01-12  16.170000  16.700001  16.020000  16.700001  16.700001  4457
   9 │ 2022-01-13  16.500000  17.129999  16.360001  16.750000  16.750000  4435 ⋯
  10 │ 2022-01-14  16.660000  16.930000  16.430000  16.930000  16.930000  2748
  11 │ 2022-01-17  16.850000  17.049999  16.530001  16.770000  16.770000  1869
  ⋮  │     ⋮           ⋮          ⋮          ⋮          ⋮          ⋮           ⋱
 163 │ 2022-08-24  10.940000  11.600000  10.850000  11.300000  11.300000  7512
 164 │ 2022-08-25  11.410000  12.150000  11.310000  11.920000  11.920000  1043 ⋯
 165 │ 2022-08-26  12.010000  12.200000  11.350000  11.480000  11.480000  1220
 166 │ 2022-08-29  11.290000  11.600000  11.010000  11.090000  11.090000  1099
 167 │ 2022-08-30  11.440000  11.510000  10.240000  10.400000  10.400000  1518
 168 │ 2022-08-31  10.480000  10.680000  10.030000  10.100000  10.100000  1233 ⋯
 169 │ 2022-09-01  10.050000  10.390000  9.680000   10.260000  10.260000  1213
 170 │ 2022-09-02  10.460000  10.500000  9.920000   9.990000   9.990000   1193
 171 │ 2022-09-05  10.090000  10.120000  9.880000   10.030000  10.030000  4671
 172 │ 2022-09-06  10.050000  10.140000  9.390000   9.520000   9.520000   1074 ⋯
                                                   1 column and 151 rows omitted

In [10]:
# Mudar os tipos das variáveis
#using Dates
df.Date = Date.(df.Date, "yyyy-mm-dd")
df.Open = parse.(Float64, df.Open)
df.High = parse.(Float64, df.High)
df.Low = parse.(Float64, df.Low)
df.Close = parse.(Float64, df.Close)
df.Adj_Close = parse.(Float64, df.Adj_Close)
df.Volume = parse.(Float64, df.Volume)
first(df,5)

5×7 DataFrame
 Row │ Date        Open     High     Low      Close    Adj_Close  Volume
     │ Date        Float64  Float64  Float64  Float64  Float64    Float64
─────┼─────────────────────────────────────────────────────────────────────
   1 │ 2022-01-03    17.21    17.47    16.58    16.74      16.74  5.5375e6
   2 │ 2022-01-04    16.96    16.99    16.25    16.34      16.34  3.1378e6
   3 │ 2022-01-05    16.11    16.19    15.23    15.23      15.23  5.1733e6
   4 │ 2022-01-06    15.39    15.65    14.86    15.5       15.5   4.6994e6
   5 │ 2022-01-07    15.27    15.99    15.1     15.77      15.77  3.7655e6

In [11]:
# Salvar CSV
#using CSV
CSV.write("C:\\Users\\User\\Documents\\goll4.csv", df)

"C:\\Users\\User\\Documents\\goll4.csv"

### Referências
https://discourse.julialang.org/t/juliadb-split-one-column-into-n-columns/20718
https://medium.com/chifi-media/basic-get-requests-and-data-interpretation-in-julia-fa27999057f4
https://br.financas.yahoo.com/quote/GOLL4.SA/history?p=GOLL4.SA
https://query1.finance.yahoo.com/v7/finance/download/GOLL4.SA?period1=1640995200&period2=1662508800&interval=1d&events=history&includeAdjustedClose=true
https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/historico/mercado-a-vista/series-historicas/
https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/cotacoes/acoes.htm
https://discourse.julialang.org/t/update-string-with-variables/52024/5
https://www.geeksforgeeks.org/splitting-string-into-array-of-substrings-in-julia-split-and-rsplit-method/
https://www.geeksforgeeks.org/replace-a-substring-with-another-string-in-julia-replace-method/
https://stackoverflow.com/questions/51902626/rename-dataframe-column-names-julia-v1-0
https://stackoverflow.com/questions/57599906/how-to-separate-a-dataframe-column-in-two-given-a-delimiter
https://stackoverflow.com/questions/62750879/how-to-convert-string-series-to-datetime-series-in-julia